### ISSUE TITLE
Create bucket if it does not exist

### ISSUE THREAD

**Issue by remche** [uktrade/jupyters3#13]
It could be handy to create the bucket if it does not exist (opt-in behavior ?). In our case, we would like to create a bucket per JupyterHub user, on first time they run a singleuser instance.
I'm not familliar with Tornado but I could try to do a PR if needed.

Thanks for you clean work on this !

**Comment by michalc** [comment]
Hi @remche,

Thanks for the suggestion. However, at the moment, I think I'm going to say no to this. Essentially because:

- I don't foresee needing this feature myself

- I would also recommend against having a bucket per user, and instead a single bucket, but having a key prefix per user. For one thing, there is one global namespace for S3 buckets across _all_ AWS accounts, so someone else could have taken whatever bucket name you might come up with. For another, there is never a need to "create" a prefix like you need to create a bucket. You just PUT objects with keys that starts with that prefix. So there is less to setup.

Thanks,

Michal
